Analyze flats to sell in KR
HoretskaKris/Apartment_Prices_in_KR-PL- pull request #3
Opened 2024-11-08 15:36 UTC by HoretskaKris

Data analysis and visualization of apartment sales in Krakow have been conducted, along with providing analytical insights.

2024-11-09 20:16 UTC, OlehTkachenko requested changes
Added some reviews to RewiewNB. BTW Really nice alalysis, every time better and beeter. Nice work!

2024-11-09 20:16 UTC, uItramarine commented on analysis_visualization_krakow_2023_2024.py
> +                              == city_name.lower()]
Why you concat all dfs and after filter big one? Mb it will be better to make this filter in for loop?

2024-11-09 20:16 UTC, uItramarine commented on analysis_visualization_krakow_2023_2024.py
> +def visualize_avg_price_per_sqm_on_map(data):
What type of data value? DataFrame?

2024-11-09 20:16 UTC, uItramarine commented on analysis_visualization_krakow_2023_2024.py
> +    krakow_map = folium.Map(location=[50.0614, 19.9366], zoom_start=12)
What the magic numbers in `location`?

2024-11-09 20:16 UTC, OlehTkachenko commented on analysis_visualization_krakow_2023_2024.py
> +                  icon=folium.Icon(color='red')).add_to(krakow_map)
Same magic numbers

2024-11-10 15:04 UTC, HoretskaKris commented on analysis_visualization_krakow_2023_2024.py
> +                              == city_name.lower()]
+

2024-11-10 15:43 UTC, HoretskaKris commented on analysis_visualization_krakow_2023_2024.py
> +def visualize_avg_price_per_sqm_on_map(data):
+add typing

2024-11-10 15:47 UTC, HoretskaKris commented on analysis_visualization_krakow_2023_2024.py
> +    krakow_map = folium.Map(location=[50.0614, 19.9366], zoom_start=12)
+ Added automatic determination of the geographic coordinates of the city center based on its name.

2024-11-10 15:47 UTC, HoretskaKris commented on analysis_visualization_krakow_2023_2024.py
> +                  icon=folium.Icon(color='red')).add_to(krakow_map)
+

2024-11-10 16:14 UTC, HoretskaKris commented
Added automatic city geolocation determination, added typing, added English description

2024-11-10 20:28 UTC, uItramarine approved these changes
LGTM

2024-11-11 12:51 UTC, merged